#########1#########1#########1#########1#########1#########1#########1#########1
apt_ppas:
  - ppa:apptainer/ppa

apt_packages:
  - ansible                   # Provisioning automation tool
  - apptainer                 # Singularity replacement
  - aria2                     # wget improvement 
  - brave-browser             # Web browser
  - curl                      # Command-line tool for HTTP requests
  - ncdu                      # Disk usage TUI
  - fonts-firacode            # Monospaced font with ligatures
  - fonts-hack                #
  - git                       # Version control system
  - gh                        # GitHub command line tool
  - htop                      # Interactive process viewer
  - hunspell                  # Spell checker library
  - hunspell-en-us            # English dictionary for Hunspell
  - jq                        # JSON processor
  - libtool-bin               # vterm prereq
  - okular                    # Universal document viewer (PDF, ePub, etc.)
  - pandoc                    # Document converter (Markdown, LaTeX, etc.)
  - parallel
  - rename
  - syncthing                 # Continuous file synchronization
  - texlive-full              # Complete LaTeX distribution
  - tree                      # Directory structure viewer
  - ttf-mscorefonts-installer # Microsoft TrueType fonts
  - vim                       # Advanced text editor
  
directory_structure:
  - "${HOME}/repos"
  - "${HOME}/.emacs.d/snippets"
  - "${HOME}/.emacs.d/lisp"
  - "${HOME}/.emacs.d/config"

  
public_symlinks:
  - src: "${HOME}/repos/basecamp/emacs/init.el"
    dest: "${HOME}/.emacs.d/init.el"
  - src: "${HOME}/repos/basecamp/emacs/load-first.el"
    dest: "${HOME}/.emacs.d/load-first.el"
  - src: "${HOME}/repos/basecamp/emacs/load-last.el"
    dest: "${HOME}/.emacs.d/load-last.el"
  - src: "${HOME}/repos/basecamp/emacs/public_yasnippets"
    dest: "${HOME}/.emacs.d/snippets/public_yasnippets"
  - src: "${HOME}/repos/basecamp/lib/lisp_functions.el"
    dest: "${HOME}/.emacs.d/lisp/lisp_functions.el"
  - src: "${HOME}/repos/basecamp/emacs/public_config.el"
    dest: "${HOME}/.emacs.d/config/public_config.el"
  - src: "${HOME}/repos/basecamp/emacs/essh.el"
    dest: "${HOME}/.emacs.d/lisp/essh.el"
  - src: "${HOME}/repos/basecamp/emacs/ob-mermaid.el"
    dest: "${HOME}/.emacs.d/lisp/ob-mermaid.el"
  - src: "${HOME}/repos/basecamp/lib/basecamp_functions.sh"
    dest: "${HOME}/.local/lib/mylibs/basecamp_functions.sh"

wget_downloads:
  - src: https://www.emacswiki.org/emacs/download/essh.el
    dest: "${HOME}/repos/basecamp/emacs/essh.el"
  - src: https://raw.githubusercontent.com/arnm/ob-mermaid/refs/heads/master/ob-mermaid.el
    dest: "${HOME}/repos/basecamp/emacs/ob-mermaid.el"
