---
- name: Docker Playbook
  hosts: all
  tasks:

    - name: Perform sudo install tasks
      block:

        - name: Update package list
          apt:
            update_cache: yes

        - name: Install required packages
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - software-properties-common
            state: present

        - name: Add Docker's official GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present

        - name: Update package list after adding Docker repo
          apt:
            update_cache: yes

        - name: Install Docker CE
          apt:
            name: docker-ce
            state: latest

        - name: Ensure Docker service is enabled and running
          systemd:
            name: docker
            enabled: yes
            state: started

        - name: Add current user to the docker group
          user:
            name: "{{ ansible_user | default(ansible_env.USER) }}"
            groups: docker
            append: yes

      become: true
